version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - geraldo_data:/var/lib/mysql
    networks:
      - microservices-network
  zipkin:
    image: openzipkin/zipkin:2.23
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-network
  naming-server:
    image: geraldocoosta/naming-server:0.0.1-SNAPSHOT
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
volumes:
  geraldo_data: 
