
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
# router de maneira via application.yml
  cloud:
    gateway:
      routes:
      - id: bookService
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: cambioService
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
  
#O que era feito nas linhas abaixo agora vai ser 
#feito programaticamente
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true