
server:
  port: 0
  error:
    include-stacktrace: on-param
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  timelimiter:
    instances:
      default:
        cancel-running-future: false
        timeout-duration: 2s
  bulkhead:
    instances:
      default:
        # Maximo de execuções concorrentes
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        #Em 10 segundos
        limit-refresh-period: 10s
        #Só posso fazer duas requisições
        limit-for-period: 2
  retry:
    instances:
      #alterando vezes que faço a requisição, esquema de profile
      foo-bar:
        max-attempts: 5
        # Quanto tempo vai esperar para tentar fazer de novo a request
        wait-duration: 1s
        # o tempo vai ser incrementado a cada retry, como fibonacci
        enable-exponential-backoff: true
      default:
        max-attempts: 2
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas:
    - book_service
    user: root
    password: root
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
