server:
  port: 8080


spring:
  application:
    name: greeting-service
  #buscando configuracoes da aplicacao config-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
