server:
  port: 8888
  
spring:
  application:
    name: config-server
#  profiles:
#    active:
#    - native
 # configuracoes para buscar arquivos de configuracoes no git e disponibilizar na porta 8888 para outras aplicacoes
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geraldocoosta/config-server
          #username: 
          #password: 
          default-label: main
          search-paths:
          - 'greeting-service*'