name: Continuous Integration with Github

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Api Gateway Container Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Build Cambio Microservice Jar 
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice Jar 
        working-directory: ./book-service
        run: mvn clean package -DskipTests

      - name: Docker Compose Build 
        working-directory: .
        run: docker-compose build
